[package]
name = "taskfly"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
anyhow = "1"
unicode-segmentation = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"